export {buttonTitles}


var buttonTitles = [   "Procedural justice","Civil justice", "Criminal justice", "Rule of law", "Homicide", "Disappearances",
                        "Violent conflicts", "Organized conflicts", "Terrorism fatalities", "Terrorism injuries",
                        "Disappearances, conflict and terrorism", "Female genital mutilation", "Missing women",
                        "Inheritance rights for widows", "Inheritance rights for daughters", "Inheritance",
                        "Women's security", "Security and Safety", "Freedom of domestic movement", "Freedom of foreign movement",
                        "Women's movement", "Freedom of movement", "Freedom to establish religious orgnizations",
                        "Freedom to operate religious organizations", "Freedom to establish and operate religious organizations",
                        "Harassment and physical hostilities", "Legal and regulatory restrictions", "Religious freedom",
                        "Freedom of association", "Freedom of assembly", "Freedom to establish political parties",  
                        "Freedom to operate political parties", "Freedom to establish and operate political parties",
                        "Freedom to establish professional org.", "Freedom to operate professional org.", "Freedom to establish and operate professional org.",
                        "Freedom to establish educational, sporting, and cultural org.",
                        "Freedom to operate educational, sporting, and cultural org.",
                        "Freedom to establish and operate educational/sporting/cultural org.",
                        "Freedom to associate and assemble with peaceful individuals or org.",
                        "Press killed", "Press jailed", "Laws and regulations that influence media content", 
                        "Political pressures and controls on media content", "Access to cable/satellite", 
                        "Access to foreign newspapers", "State control over Internet access", "Freedom of expression",
                        "Legal gender", "Parental rights in marriage", "Parental rights after divorce",
                        "Parental rights", "Male-to-male relationships", "Female to female relationships", "Same-sex relationships",
                        "Divorce", "Identity and relationships", "Personal Freedom (Score)", "Personal Freedom (rank)", 
                        "Government consumption", "Transfers and subsidies", "Government enterprises and investments", "Top marginal income tax rate",
                        "Top marginal income and payroll tax rate", "Top marginal tax rate", "Size of government", "Judicial independence",
                        "Impartial courts", "Protection of property rights", "Military interference in rule of law and politics",
                        "Integrity of the legal system", "Legal enforcement of contracts", "Regulatory restrictions on the sale of real property",
                        "Reliability of police", "Business costs of crime", "Gender adjustment", "Legal system and property rights",
                        "Money growth", "Standard deviation of inflation", "Inflation: most recent year", "Freedom to own foreign currency bank account",
                        "Revenue from trade taxes (% of trade sector)", "Mean tariff rate", "Standard deviation of tariffs rates", "Tariffs", "Nontariff trade barriers",
                        "Compliance costs of importing and exporting", "Regulatory trade barriers", "Black-market exchange rates",
                        "Foreign ownership/investment restrictions", "Capital controls", "Freedom of foreigners to visit", "Controls of the movement of capital and people",
                        "Freedom to trade internationally", "Ownership of banks", "Private sector credit", "Interest rate controls",
                        "Credit market regulations", "Hiring regulations and minimum wage", "Hiring and firing regulations", "Centralized collective bargaining",
                        "Hours regulations", "Mandated cost of worker dismissal", "Conscription", "Labor market regulations",
                        "Administrative requirements", "Bureaucracy costs", "Starting a business", "Extra payments/bribes/favoritism",
                        "Licensing restrictions", "Cost of tax compliance", "Business regulations", "Regulation", "Economic Freedom (score)",
                        "Economic Freedom (rank)", "Human Freedom (score)", "Human Freedom (rank)", "Human Freedom (quantile)"]
